# Nome da nossa aplicação (Ajustado para o seu Artifact)
spring.application.name=jason-ferraz-os

# Configuração do Banco de Dados H2
# O nome 'jason-os-db' é apenas o nome do banco na memória, pode ser qualquer um
spring.datasource.url=jdbc:h2:mem:jason-os-db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Ativa o Console do H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true